import { CountryMeta, CountryCode } from '../types/calendar';

export const COUNTRY_META: Record<CountryCode, CountryMeta> = {
  KR: { label: 'Korea', labelLocal: '대한민국', color: 'bg-sky-500', flag: '🇰🇷' },
  UK: { label: 'United Kingdom', labelLocal: 'United Kingdom', color: 'bg-rose-500', flag: '🇬🇧' },
  US: { label: 'United States', labelLocal: 'United States', color: 'bg-blue-600', flag: '🇺🇸' },
  CA: { label: 'Canada', labelLocal: 'Canada', color: 'bg-red-600', flag: '🇨🇦' },
  AU: { label: 'Australia', labelLocal: 'Australia', color: 'bg-amber-500', flag: '🇦🇺' },
  NZ: { label: 'New Zealand', labelLocal: 'New Zealand', color: 'bg-slate-700', flag: '🇳🇿' },
  IE: { label: 'Ireland', labelLocal: 'Ireland', color: 'bg-green-600', flag: '🇮🇪' },
  FR: { label: 'France', labelLocal: 'France', color: 'bg-blue-500', flag: '🇫🇷' },
  DE: { label: 'Germany', labelLocal: 'Deutschland', color: 'bg-slate-800', flag: '🇩🇪' },
  JP: { label: 'Japan', labelLocal: '日本', color: 'bg-red-500', flag: '🇯🇵' },
  CN: { label: 'China', labelLocal: '中国', color: 'bg-red-700', flag: '🇨🇳' },
  BR: { label: 'Brazil', labelLocal: 'Brasil', color: 'bg-green-500', flag: '🇧🇷' },
  IN: { label: 'India', labelLocal: 'भारत', color: 'bg-orange-500', flag: '🇮🇳' },
  GR: { label: 'Greece', labelLocal: 'Ελλάδα', color: 'bg-blue-400', flag: '🇬🇷' },
  ES: { label: 'Spain', labelLocal: 'España', color: 'bg-yellow-500', flag: '🇪🇸' },
  PT: { label: 'Portugal', labelLocal: 'Portugal', color: 'bg-emerald-600', flag: '🇵🇹' },
  LU: { label: 'Luxembourg', labelLocal: 'Luxembourg', color: 'bg-cyan-500', flag: '🇱🇺' },
  DK: { label: 'Denmark', labelLocal: 'Danmark', color: 'bg-red-600', flag: '🇩🇰' },
  FI: { label: 'Finland', labelLocal: 'Suomi', color: 'bg-blue-300', flag: '🇫🇮' },
  HU: { label: 'Hungary', labelLocal: 'Magyarország', color: 'bg-green-700', flag: '🇭🇺' },
  EE: { label: 'Estonia', labelLocal: 'Eesti', color: 'bg-slate-600', flag: '🇪🇪' },
  IS: { label: 'Iceland', labelLocal: 'Ísland', color: 'bg-indigo-400', flag: '🇮🇸' },
  SE: { label: 'Sweden', labelLocal: 'Sverige', color: 'bg-yellow-400', flag: '🇸🇪' },
  QA: { label: 'Qatar', labelLocal: 'قطر', color: 'bg-purple-600', flag: '🇶🇦' },
  LT: { label: 'Lithuania', labelLocal: 'Lietuva', color: 'bg-amber-600', flag: '🇱🇹' },
  RO: { label: 'Romania', labelLocal: 'România', color: 'bg-yellow-600', flag: '🇷🇴' },
  RU: { label: 'Russia', labelLocal: 'Россия', color: 'bg-blue-700', flag: '🇷🇺' },
  UZ: { label: 'Uzbekistan', labelLocal: 'Oʻzbekiston', color: 'bg-teal-500', flag: '🇺🇿' },
  ID: { label: 'Indonesia', labelLocal: 'Indonesia', color: 'bg-red-500', flag: '🇮🇩' },
  KH: { label: 'Cambodia', labelLocal: 'កម្ពុជា', color: 'bg-blue-600', flag: '🇰🇭' },
  PK: { label: 'Pakistan', labelLocal: 'پاکستان', color: 'bg-green-600', flag: '🇵🇰' },
  GE: { label: 'Georgia', labelLocal: 'საქართველო', color: 'bg-rose-600', flag: '🇬🇪' },
  AR: { label: 'Argentina', labelLocal: 'Argentina', color: 'bg-sky-400', flag: '🇦🇷' },
  MX: { label: 'Mexico', labelLocal: 'México', color: 'bg-green-600', flag: '🇲🇽' },
  TH: { label: 'Thailand', labelLocal: 'ประเทศไทย', color: 'bg-blue-500', flag: '🇹🇭' },
  PH: { label: 'Philippines', labelLocal: 'Pilipinas', color: 'bg-blue-400', flag: '🇵🇭' },
  VN: { label: 'Vietnam', labelLocal: 'Việt Nam', color: 'bg-red-600', flag: '🇻🇳' },
  BH: { label: 'Bahrain', labelLocal: 'البحرين', color: 'bg-red-700', flag: '🇧🇭' },
  MY: { label: 'Malaysia', labelLocal: 'Malaysia', color: 'bg-yellow-500', flag: '🇲🇾' },
};

export const FR_REGION_META = [
  { key: 'AM', label: 'Alsace–Moselle' },
  { key: 'RE', label: 'La Réunion' },
  { key: 'GP', label: 'Guadeloupe' },
  { key: 'MQ', label: 'Martinique' },
  { key: 'GF', label: 'Guyane' },
  { key: 'YT', label: 'Mayotte' },
  { key: 'NC', label: 'Nouvelle-Calédonie' },
  { key: 'PF', label: 'Polynésie française' },
  { key: 'WF', label: 'Wallis‑et‑Futuna' },
];

export const WEEK_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
